#!/bin/bash

## $NGINXSOURCE/BAUEN / 20160426
## Marianne Spiller <github@spiller.me>
## Used to build nginx-1.9.15 with needed dependencies

./configure \
--add-module=/usr/src/ngx_pagespeed-release-1.11.33.0-beta \
--add-module=/usr/src/nginx-auth-ldap/ \
--prefix=/opt/local \
--conf-path=/etc/nginx/ \
--user=www-data \
--group=www-data \
--with-http_ssl_module \
--with-http_realip_module \
--with-http_addition_module \
--with-http_sub_module \
--with-http_dav_module \
--with-http_flv_module \
--with-http_mp4_module \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-http_random_index_module \
--with-http_secure_link_module \
--with-http_stub_status_module \
--with-http_auth_request_module \
--with-mail \
--with-mail_ssl_module \
--with-file-aio \
--with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' \
--with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed' \
--with-ipv6
